### ISSUE TITLE
wont accept arguments

### ISSUE THREAD

**Issue by cunninr2** [hibikiledo/AM2320#2]
can you tel me if this is a bug please.   

when compiling on arduino for ESP32, the following code will not accept the SDA,SCL arguments.

// Include library into the sketch
#include "AM2320.h"

// Create an instance of sensor
AM2320 sensor;

void setup()
{
  // enable serial communication
  Serial.begin(115200);
  // call sensor.begin() to initialize the library
  sensor.begin(5, 4);
}

The error shows as : 
C:\Users\robert\Documents\Arduino\libraries\AM2320-master/AM2320.h:35:14: note:   candidate expects 0 arguments, 2 provided

exit status 1
no matching function for call to 'AM2320::begin(int, int)'

**Comment by hibikiledo** [comment]
Yes, it is a bug.

I have updated the library.
https://github.com/hibikiledo/AM2320/releases/tag/V1.1

Please let me know if it works for you.

**Comment by cunninr2** [comment]
brilliant. works perfectly now. Many thanks for the quick fix.
