### ISSUE TITLE
Negative temperature

### ISSUE THREAD

**Issue by nadvornik** [hibikiledo/AM2320#5]
I have noticed that the library does not return negative temperatures correctly. For example, it returns 3 degrees instead of -3.

**Comment by hibikiledo** [comment]
Hi @nadvornik , I have investigated and attempted to fix the issue.

If you are available to test the fix, download the patched version of the library below. 
https://github.com/hibikiledo/AM2320/archive/fix-negative-temp-support.zip

Please report back if this resolves your issue so I can release it.

Thank you :)

**Comment by gjkrediet** [comment]
@hbk Thanks for you work. I ran two years later into this same problem (no negative temperature) and found the same solution which works. Would it be possible for you to create an updated version?

**Comment by hibikiledo** [comment]
@gjkrediet I've published a new version. I don't own AM2320 anymore so It is great to know that the solution works. 👍

**Comment by gjkrediet** [comment]
Thanks a lot!

 

Van: @hbk ***@***.***> 
Verzonden: zaterdag 10 december 2022 13:07
Aan: hibikiledo/AM2320 ***@***.***>
CC: gjkrediet ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [hibikiledo/AM2320] Negative temperature (#5)

 

@gjkrediet <https://github.com/gjkrediet>  I've published a new version. I don't own AM2320 anymore so It is great to know that the solution works. 👍
